In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/data.csv")  # adjust filename if needed

df.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>TransactionId</th>
      <th>BatchId</th>
      <th>AccountId</th>
      <th>SubscriptionId</th>
      <th>CustomerId</th>
      <th>CurrencyCode</th>
      <th>CountryCode</th>
      <th>ProviderId</th>
      <th>ProductId</th>
      <th>ProductCategory</th>
      <th>ChannelId</th>
      <th>Amount</th>
      <th>Value</th>
      <th>TransactionStartTime</th>
      <th>PricingStrategy</th>
      <th>FraudResult</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>TransactionId_76871</td>
      <td>BatchId_36123</td>
      <td>AccountId_3957</td>
      <td>SubscriptionId_887</td>
      <td>CustomerId_4406</td>
      <td>UGX</td>
      <td>256</td>
      <td>ProviderId_6</td>
      <td>ProductId_10</td>
      <td>airtime</td>
      <td>ChannelId_3</td>
      <td>1000.0</td>
      <td>1000</td>
      <td>2018-11-15T02:18:49Z</td>
      <td>2</td>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>TransactionId_73770</td>
      <td>BatchId_15642</td>
      <td>AccountId_4841</td>
      <td>SubscriptionId_3829</td>
      <td>CustomerId_4406</td>
      <td>UGX</td>
      <td>256</td>
      <td>ProviderId_4</td>
      <td>ProductId_6</td>
      <td>financial_services</td>
      <td>ChannelId_2</td>
      <td>-20.0</td>
      <td>20</td>
      <td>2018-11-15T02:19:08Z</td>
      <td>2</td>
      <td>0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>TransactionId_26203</td>
      <td>BatchId_53941</td>
      <td>AccountId_4229</td>
      <td>SubscriptionId_222</td>
      <td>CustomerId_4683</td>
      <td>UGX</td>
      <td>256</td>
      <td>ProviderId_6</td>
      <td>ProductId_1</td>
      <td>airtime</td>
      <td>ChannelId_3</td>
      <td>500.0</td>
      <td>500</td>
      <td>2018-11-15T02:44:21Z</td>
      <td>2</td>
      <td>0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>TransactionId_380</td>
      <td>BatchId_102363</td>
      <td>AccountId_648</td>
      <td>SubscriptionId_2185</td>
      <td>CustomerId_988</td>
      <td>UGX</td>
      <td>256</td>
      <td>ProviderId_1</td>
      <td>ProductId_21</td>
      <td>utility_bill</td>
      <td>ChannelId_3</td>
      <td>20000.0</td>
      <td>21800</td>
      <td>2018-11-15T03:32:55Z</td>
      <td>2</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>TransactionId_28195</td>
      <td>BatchId_38780</td>
      <td>AccountId_4841</td>
      <td>SubscriptionId_3829</td>
      <td>CustomerId_988</td>
      <td>UGX</td>
      <td>256</td>
      <td>ProviderId_4</td>
      <td>ProductId_6</td>
      <td>financial_services</td>
      <td>ChannelId_2</td>
      <td>-644.0</td>
      <td>644</td>
      <td>2018-11-15T03:34:21Z</td>
      <td>2</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
df.shape
df.info()
df.describe(include="all").T

    <class 'pandas.core.frame.DataFrame'>
    RangeIndex: 95662 entries, 0 to 95661
    Data columns (total 16 columns):
     #   Column                Non-Null Count  Dtype  
    ---  ------                --------------  -----  
     0   TransactionId         95662 non-null  object 
     1   BatchId               95662 non-null  object 
     2   AccountId             95662 non-null  object 
     3   SubscriptionId        95662 non-null  object 
     4   CustomerId            95662 non-null  object 
     5   CurrencyCode          95662 non-null  object 
     6   CountryCode           95662 non-null  int64  
     7   ProviderId            95662 non-null  object 
     8   ProductId             95662 non-null  object 
     9   ProductCategory       95662 non-null  object 
     10  ChannelId             95662 non-null  object 
     11  Amount                95662 non-null  float64
     12  Value                 95662 non-null  int64  
     13  TransactionStartTime  95662 non-null  object 
     14  PricingStrategy       95662 non-null  int64  
     15  FraudResult           95662 non-null  int64  
    dtypes: float64(1), int64(4), object(11)
    memory usage: 11.7+ MB

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>count</th>
      <th>unique</th>
      <th>top</th>
      <th>freq</th>
      <th>mean</th>
      <th>std</th>
      <th>min</th>
      <th>25%</th>
      <th>50%</th>
      <th>75%</th>
      <th>max</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>TransactionId</th>
      <td>95662</td>
      <td>95662</td>
      <td>TransactionId_76871</td>
      <td>1</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>BatchId</th>
      <td>95662</td>
      <td>94809</td>
      <td>BatchId_67019</td>
      <td>28</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>AccountId</th>
      <td>95662</td>
      <td>3633</td>
      <td>AccountId_4841</td>
      <td>30893</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>SubscriptionId</th>
      <td>95662</td>
      <td>3627</td>
      <td>SubscriptionId_3829</td>
      <td>32630</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>CustomerId</th>
      <td>95662</td>
      <td>3742</td>
      <td>CustomerId_7343</td>
      <td>4091</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>CurrencyCode</th>
      <td>95662</td>
      <td>1</td>
      <td>UGX</td>
      <td>95662</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>CountryCode</th>
      <td>95662.0</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>256.0</td>
      <td>0.0</td>
      <td>256.0</td>
      <td>256.0</td>
      <td>256.0</td>
      <td>256.0</td>
      <td>256.0</td>
    </tr>
    <tr>
      <th>ProviderId</th>
      <td>95662</td>
      <td>6</td>
      <td>ProviderId_4</td>
      <td>38189</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>ProductId</th>
      <td>95662</td>
      <td>23</td>
      <td>ProductId_6</td>
      <td>32635</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>ProductCategory</th>
      <td>95662</td>
      <td>9</td>
      <td>financial_services</td>
      <td>45405</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>ChannelId</th>
      <td>95662</td>
      <td>4</td>
      <td>ChannelId_3</td>
      <td>56935</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Amount</th>
      <td>95662.0</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>6717.846433</td>
      <td>123306.797164</td>
      <td>-1000000.0</td>
      <td>-50.0</td>
      <td>1000.0</td>
      <td>2800.0</td>
      <td>9880000.0</td>
    </tr>
    <tr>
      <th>Value</th>
      <td>95662.0</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>9900.583941</td>
      <td>123122.087776</td>
      <td>2.0</td>
      <td>275.0</td>
      <td>1000.0</td>
      <td>5000.0</td>
      <td>9880000.0</td>
    </tr>
    <tr>
      <th>TransactionStartTime</th>
      <td>95662</td>
      <td>94556</td>
      <td>2018-12-24T16:30:13Z</td>
      <td>17</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>PricingStrategy</th>
      <td>95662.0</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>2.255974</td>
      <td>0.732924</td>
      <td>0.0</td>
      <td>2.0</td>
      <td>2.0</td>
      <td>2.0</td>
      <td>4.0</td>
    </tr>
    <tr>
      <th>FraudResult</th>
      <td>95662.0</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>0.002018</td>
      <td>0.044872</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1.0</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
missing = df.isnull().sum().sort_values(ascending=False)
missing[missing > 0]





    Series([], dtype: int64)

In [ ]:
import matplotlib.pyplot as plt

df["Amount"].hist(bins=50)
plt.title("Distribution of Transaction Amount")
plt.show()

df["Value"].hist(bins=50)
plt.title("Distribution of Transaction Value")
plt.show()

![png](output_3_0.png)

![png](output_3_1.png)

In [ ]:
df["ProductCategory"].value_counts().head(10).plot(kind="bar")
plt.title("Top Product Categories")
plt.show()

df["ChannelId"].value_counts().plot(kind="bar")
plt.title("Transaction Channels")
plt.show()

![png](output_4_0.png)

![png](output_4_1.png)

In [ ]:
num_df = df.select_dtypes(include=np.number)

corr = num_df.corr()

import seaborn as sns

plt.figure(figsize=(10,6))
sns.heatmap(corr, annot=False, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

![png](output_5_0.png)

In [ ]:
import seaborn as sns

sns.boxplot(x=df["Amount"])
plt.title("Outliers in Amount")
plt.show()

![png](output_6_0.png)

In [ ]:
sns.boxplot(x=df["Value"])
plt.title("Outliers in Value")
plt.show()

![png](output_7_0.png)